#!/bin/bash
# Generate env.sh configuration file for remote deployment
#
# Usage: ./scripts/generate-env.sh [OPTIONS]
#   --phaser-root PATH    Phaser installation path (required)
#   --erigon-root PATH    Erigon installation path (required)
#   --output PATH         Output file (default: stdout)
#   --help                Show this help
#
# Example:
#   ./scripts/generate-env.sh \
#     --phaser-root /mnt/nvme-raid/phaser \
#     --erigon-root /mnt/nvme-raid/erigon-customized \
#     --output env.sh
#
#   # Then copy to remote
#   scp env.sh myserver:/mnt/nvme-raid/phaser/config/
#   ssh myserver "cp /mnt/nvme-raid/phaser/config/env.sh /mnt/nvme-raid/erigon-customized/config/"

set -e

PHASER_ROOT=""
ERIGON_ROOT=""
OUTPUT=""

# Parse args
while [[ $# -gt 0 ]]; do
    case $1 in
        --phaser-root) PHASER_ROOT="$2"; shift 2 ;;
        --erigon-root) ERIGON_ROOT="$2"; shift 2 ;;
        --output|-o) OUTPUT="$2"; shift 2 ;;
        --help|-h)
            echo "Usage: $0 [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --phaser-root PATH    Phaser installation path (required)"
            echo "  --erigon-root PATH    Erigon installation path (required)"
            echo "  --output PATH         Output file (default: stdout)"
            echo ""
            echo "Example:"
            echo "  $0 --phaser-root /mnt/nvme-raid/phaser --erigon-root /mnt/nvme-raid/erigon-customized -o env.sh"
            echo ""
            echo "  # Then copy to remote"
            echo "  scp env.sh myserver:/mnt/nvme-raid/phaser/config/"
            echo "  ssh myserver \"mkdir -p /mnt/nvme-raid/erigon-customized/config && cp /mnt/nvme-raid/phaser/config/env.sh /mnt/nvme-raid/erigon-customized/config/\""
            exit 0 ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

# Validate required args
if [[ -z "$PHASER_ROOT" ]]; then
    echo "Error: --phaser-root is required" >&2
    exit 1
fi

if [[ -z "$ERIGON_ROOT" ]]; then
    echo "Error: --erigon-root is required" >&2
    exit 1
fi

# Generate config
generate_config() {
    cat << EOF
# Phaser environment configuration
# Generated by: scripts/generate-env.sh
# Date: $(date -Iseconds)
#
# This file is sourced by run-full-sync.sh and start-erigon.sh
# Place copies in:
#   $PHASER_ROOT/config/env.sh
#   $ERIGON_ROOT/config/env.sh

export PHASER_ROOT="$PHASER_ROOT"
export ERIGON_ROOT="$ERIGON_ROOT"
EOF
}

# Output
if [[ -n "$OUTPUT" ]]; then
    generate_config > "$OUTPUT"
    echo "Generated: $OUTPUT" >&2
else
    generate_config
fi
