{
 "title": "phaser ",
 "time": { "from": "2025-11-07T15:20:49.622Z", "to": "2025-11-08T06:15:30.095Z" },
 "panels": [
  {
   "title": "Active Blocks Request times (ms)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "  sum by (segment_num) (\n    rate(erigon_bridge_grpc_request_duration_blocks_milliseconds_sum[1m])\n  ) > 0\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Transaction Request times (ms)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "  sum by (segment_num) (\n    rate(erigon_bridge_grpc_request_duration_transactions_milliseconds_sum[1m])\n  ) > 0\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Logs Request times (ms)",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "  sum by (segment_num) (\n    rate(erigon_bridge_grpc_request_duration_logs_milliseconds_sum[1m])\n  ) > 0\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bridge Workers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "targets": [
    { "expr": "erigon_bridge_active_workers", "legendFormat": "{{phase}}" }
   ]
  },
  {
   "title": "Bridge GRPC streams",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "erigon_bridge_grpc_streams_active",
     "legendFormat": "{{stream_type}}"
    }
   ]
  },
  {
   "title": "Query sync workers and queue",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "targets": [
    { "expr": "phaser_query_active_workers", "legendFormat": "{{phase}} workers" },
    {
     "expr": "phaser_query_segment_retry_count",
     "legendFormat": "__auto"
    },
    { "expr": "phaser_query_sync_queue_depth", "legendFormat": "{{phase}}" },
    { "expr": "phaser_query_errors_total", "legendFormat": "{{phase}}" }
   ]
  },
  {
   "title": "bridge segments",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "erigon_bridge_segment_attempts_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "erigon_bridge_segment_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bridge Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 39 },
   "targets": [
    { "expr": "erigon_bridge_errors_total", "legendFormat": "__auto" }
   ]
  }
 ]
}